#!/bin/bash
#SBATCH -p 3090-gcondo
#SBATCH -N 1
#SBATCH --mem=128G
#SBATCH -n 32
#SBATCH --time=12:00:00

#SBATCH -o evaluate-methods.out


module load gcc/10.2
module load cuda/11.3.1
module load python/3.7.4
module load java/8u111
source /users/gmurtaza/GrapHiC/grapHiC/bin/activate


python -u evaluate_methods.py
