#!/bin/bash
#SBATCH -p gpu --gres=gpu:1 --constraint="ampere"
#SBATCH -N 1
#SBATCH --mem=128G
#SBATCH -n 8
#SBATCH --time=12:00:00

#SBATCH -o graphic-positional.out


module load gcc/10.2
module load cuda/11.3.1
module load python/3.7.4
module load java/8u111
source /users/gmurtaza/GrapHiC/grapHiC/bin/activate

python -u grapHiC_positional.py
