#!/bin/bash
#SBATCH -p 3090-gcondo --gres=gpu:1
#SBATCH -J GrapHiC

# Ensures all allocated cores are on the same node
#SBATCH -N 1
#SBATCH -c 32
#SBATCH --mem=512G

#SBATCH -t 04:00:00
#SBATCH -o main.out

# Load modules
module load gcc/8.3
module load cuda/10.2
module load anaconda/2020.02
source /gpfs/runtime/opt/anaconda/2020.02/etc/profile.d/conda.sh

# Activate the virtual environment
conda activate grapHiC

conda env export


# nvcc --version
# nvidia-smi --query-gpu=gpu_name --format=csv

# Load python virtual environment 
# source /users/gmurtaza/GrapHiC/grapHiC/bin/activate

# Run the program 
# python main.py


