#!/bin/bash
#SBATCH -p 3090-gcondo --gres=gpu:1
#SBATCH -N 1

#SBATCH -n 32
#SBATCH --mem=512G
#SBATCH --time=04:00:00

#SBATCH -o oscar.out


module load gcc/10.2
module load cuda/11.3.1
module load python/3.7.4
source /users/gmurtaza/GrapHiC/grapHiC/bin/activate

python main.py