#!/bin/bash
#SBATCH -p 3090-gcondo --gres=gpu:1
#SBATCH -J GrapHiC

# Ensures all allocated cores are on the same node
#SBATCH -N 1
#SBATCH -c 32
#SBATCH --mem=512G

#SBATCH -t 04:00:00
#SBATCH -o main.out

# Load modules
module load gcc/10.2
module load cuda/11.3.1

# Activate the virtual environment
# nvcc --version
# nvidia-smi --query-gpu=gpu_name --format=csv

# Load python virtual environment 
source /users/gmurtaza/GrapHiC/grapHiC/bin/activate

# Run the program 
python main.py


